language: cpp

compiler: gcc

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libboost-filesystem-dev libboost-log-dev libboost-system libssl-dev

before_script:
  - svn co http://libtorrent.googlecode.com/svn/tags/libtorrent-1_0_3 libtorrent
  - cd libtorrent
  - ./autotool.sh
  - ./configure --enable-deprecated-functions=no
  - make
  - sudo make install
  - cd ..
  - mkdir build
  - cd build
  - cmake ..

script: make

notifications:
  email:
    recipients:
      - viktor+travisci@viktorelofsson.se
    on_success: change
    on_failure: always
