language: cpp

compiler: gcc

before_install:
 - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ trusty main universe"
 - sudo apt-get clean
 - sudo apt-get update -qq
 - sudo apt-get install -qq cmake libboost-date-time-dev libboost-filesystem-dev libboost-log-dev libboost-program-options-dev libboost-regex-dev libboost-system-dev libboost-thread-dev libssl-dev libv8-dev
 - if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq libstdc++-4.8-dev; fi
 - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
 - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

before_script:
  - svn co http://libtorrent.googlecode.com/svn/tags/libtorrent-1_0_3 libtorrent
  - cd libtorrent
  - ./autotool.sh
  - ./configure --enable-deprecated-functions=no
  - make
  - sudo make install
  - cd ..
  - mkdir build
  - cd build
  - cmake ..

script: make

notifications:
  email:
    recipients:
      - viktor+travisci@viktorelofsson.se
    on_success: change
    on_failure: always
