language: cpp

compiler: gcc
sudo: false

cache:
  directories:
  - $HOME/boost
  - $HOME/libtorrent

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_install:
- bash linux/install-boost.sh
- bash linux/install-libtorrent.sh

before_script:
- export CC=/usr/bin/gcc-4.8
- export CXX=/usr/bin/g++-4.8
- export CPATH=$HOME/boost/include
- export CPATH=$CPATH:$HOME/libtorrent/include
- export LIBRARY_PATH=$HOME/boost/lib
- export LIBRARY_PATH=$LIBRARY_PATH:$HOME/libtorrent/lib
- git submodule update --init --recursive

script: linux/build.sh

notifications:
  email:
    recipients:
      - viktor+travisci@viktorelofsson.se
    on_success: change
    on_failure: always
